### ISSUE TITLE
option to skip symlinks

### ISSUE THREAD

**Issue by fpedroza** [mnagel/clustergit#14]
Would love the ability to skip symlinks.  I hope to find time to investigate this myself, but time will tell.
Great tool!

**Comment by anestisb** [comment]
Implemented something similar recently. Have a look at https://github.com/anestisb/clustergit/commit/355b3ff93ad38ed067882a3c3cfae9db37a1145e if you're still interested.

If project maintainers are interested to upstream this feature feel to copy the code across or ask for a pull request.

**Comment by mnagel** [comment]
wow, found this when doing some cleanup. if this is still of interest, I would accept a pull request, otherwise I'd close the ticket...
