### ISSUE TITLE
add possibility to skip directories

### ISSUE THREAD

**Issue by matkoniecz** [mnagel/clustergit#15]
I scan entire filesystem - but there are certain known directories that have uncommitted changes and it is acceptable (for example clone of https://github.com/StevenBlack/hosts, with update scheduled in cron, location that keeps [partial/modified copy of real repository](https://github.com/matkoniecz/CartoCSSHelper/issues/9) what is not a cause for alarm etc).

Currently I have no idea how this option should be named `--except` with short version `-e` collides a bit with `--execute`.

**Comment by mnagel** [comment]
folders can already be excluded via regex:

```
  -e EXCLUDE, --exclude EXCLUDE
                        Regex to exclude directories
```

example:

```
nailor@sting:*clustergit/doc/demo$ clustergit                        
Starting git status...
Scanning sub directories of .
./arepo                                 : Clean
./clustergit                            : No Changes, Unpushed commits
./clustergit-clean                      : Clean
./repo1                                 : Changes
./repo2                                 : On branch otherbranch, Changes
./repo3                                 : Clean
Done
nailor@sting:*clustergit/doc/demo$ clustergit -e "^.{1,10}repo[^2]*$"
Starting git status...
Scanning sub directories of .
./clustergit                            : No Changes, Unpushed commits
./clustergit-clean                      : Clean
./repo2                                 : On branch otherbranch, Changes
Done
```

what else do you need?

**Comment by mnagel** [comment]
I will close this, as I think it is possible already. Please comment/reopen if more action is needed.

**Comment by matkoniecz** [comment]
Thanks for pointing it out! It works fine.
