### ISSUE TITLE
Showing repository as clean with unpushed commits and unpulled commits

### ISSUE THREAD

**Issue by dimitrieh** [mnagel/clustergit#21]
@mnagel as you can see here. I have a repository with unpushed commits and unpulled commits..

![image](https://cloud.githubusercontent.com/assets/429659/24970913/4edd1640-1fb6-11e7-9467-232c4def0554.png)

clustergit shows all projects as clean though...

How is this possible?

**Comment by dimitrieh** [comment]
verbose output doesn't clear things up

![image](https://cloud.githubusercontent.com/assets/429659/24971029/bbc87b32-1fb6-11e7-8db4-57a3d0aab120.png)

**Comment by dimitrieh** [comment]
running `clustergit -R --warn-unversioned -d ~/projects --exec 'git status -sb'` gives me a similar result, but shows what's wrong more clearly

![image](https://cloud.githubusercontent.com/assets/429659/24972458/c0942206-1fbb-11e7-89ff-e1b766d13386.png)

**Comment by mnagel** [comment]
clustergit runs `LC_ALL=C git status` in the folder 

it prints "Unpushed commits" `if 'Your branch is ahead of' in out:`

So what exactly do you get for that command in the directory in question?

**Comment by dimitrieh** [comment]
@mnagel it shows this ;)

![image](https://cloud.githubusercontent.com/assets/429659/25381734/836b3ed4-29d2-11e7-9f84-12f113609df2.png)

while it shows the repo as clean with clustergit

**Comment by mnagel** [comment]
as indicated by the `nothing to commit, working tree clean` in the output of git status above, the tree IS clean and clustergit reports that. you might be interested in the fact that the branches have diverged, but clustergit currently does not check that.

you may have a look at the artificial intelligence (i.e. if-cascade) in https://github.com/mnagel/clustergit/blob/master/clustergit#L310 (and following lines) and suggest how to handle this case.

maybe mark as unclean and append message "diverged from upstream"?

**Comment by mnagel** [comment]
closing b/c of inactivity

**Comment by dimitrieh** [comment]
@mnagel this might be related to a line in my git config:

```
[merge]
        ff = only
```

This forces me to pull with `git pull --rebase` so i don't end up creating merge commits as my local branch has diverged from the upstream remote.

basically the following situation (11 comits incoming, 1 that should be pushed, which has been diverged):
![image](https://user-images.githubusercontent.com/429659/30507266-0eeec3ec-9a83-11e7-82f5-b7010606816f.png)

So basically we should see if ff pull is possible on branch... 

if possible for every local branch.. see if it is possible (this way you would spot hidden local changes.. which have not been pushed yet, as you changed branch)

I would say display it as `diverged from upstream` + `unpushed commits` (if any changes are also uncommited + `changes`

For multiple branches: all of these features could go of course...  i would add `(+3 additional branches)`

wdyt
