### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by 1j01** [mnagel/clustergit#24]
I made a batch file `clustergit.cmd` so I could add the program to my `PATH` on Windows:

```batch
@echo off
python "%~dp0\clustergit" %*
```

It wasn't getting any output from the commands, maybe because of the `&&` usage.
I was able to remedy this by pasting in some code from [an SO answer](https://stackoverflow.com/a/28483026/2624876):

```python
from subprocess import check_output, CalledProcessError, STDOUT

def get_status_output(cmd):
    try:
        output = check_output(cmd, shell=True, universal_newlines=True, stderr=STDOUT)
        status = 0
    except CalledProcessError as ex:
        output = ex.output
        status = ex.returncode
    if output[-1:] == '\n':
        output = output[:-1]
    return status, output
```

This code can go away:
```python
try:
    import commands
except Exception:
    # python3
    import subprocess as commands
    commands.get_output = commands.check_output
```

Also I added a bit of error handling for the lack of output:
```python
            if len(out) is 0:
                raise ChildProcessError('No output from child process')
```
I'm not sure whether that should be a `ChildProcessError` or a `ValueError` or just an `Exception`.

**Comment by mnagel** [comment]
#25 has been merged
