### ISSUE TITLE
Process symlinked dirs

### ISSUE THREAD

**Issue by fpedroza** [mnagel/clustergit#29]
The --recursive option doesn't seem to work across a symlinked directory structure. More specifically, I have a directory structure that I've created a symlink to within a directory I'm running clusergit --recursive in. For example:
```
.
├── dir1
│   └── repo1
└── dir2
    ├── repo2
    └── linked -> foo/dir1/
```

**Comment by mnagel** [comment]
I am not sure if this is still the case, and if foo/dir1/ is a single dir to check or another folder that should be checked recursively. please reopen with more details.
