### ISSUE TITLE
Branch option should accept a regex

### ISSUE THREAD

**Issue by iainelder** [mnagel/clustergit#34]
Github now defaults to "main" for new repos. https://github.com/github/renaming

Azure Devops wikis use "wikiMaster" for the default branch. https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-update-offline?view=azure-devops

I need to work with all three of these defaults at a time and I want clustergit to handle it.

```text
$ clustergit
Scanning sub directories of .
./Infra                          : Clean
./Infra.wiki                     : On branch wikiMaster, No Changes
./multi-region-org-config-rules-terraform: Clean
./terraform-aws-remote-state-s3-backend : Clean
./terraform-aws-secure-baseline         : Clean
./terraform-provider-aws                : On branch main, No Changes
Done
```

These should all say "clean".

The exclude option already accepts a regex.

If the branch option supported regex too, I would expect to be able to solve it like this:

```
clustergit --branch "master|main|wikiMaster"
```

The branch option default "master" continues to be sensible because of the all the existing Git repos that use it as the default branch.

**Comment by mnagel** [comment]
You can already disable branch warnings by setting `--branch ""` today.
If you want to keep the warning but have multiple acceptable mainline branches, this is not yet possible. It should be rather straightforward to add that functionality, however.

**Comment by iainelder** [comment]
Hi @mnagel , thanks for the reminder about the setting to disable it.

I had a look at the code, and yes, it looks simple enough to change, I just haven't found time to create a PR yet :-)

I would include tests as well for such a change.

**Comment by iainelder** [comment]
I've found that the `--branch ''` option to meet my needs.

I no longer plan to create a PR for this.

I'll close the issue as I no longer need the feature.

**Comment by fpedroza** [comment]
I still think there's value to supporting different main-line branches and being able to identify non-main-line repos.
