### ISSUE TITLE
Is there a timeout feature?

### ISSUE THREAD

**Issue by k4y4k** [mnagel/clustergit#35]
Howdy :wave:

For whatever reason, one of my git projects refuses to fetch - it doesn't error, it just hangs forever. (Whatever, it works when I specifically `cd` in and `fetch` myself, not a huge deal)

I thus exclude that folder with `-e folder-name`. Epic. But is there some kind of "if nothing happens for X seconds, move on" functionality? I ask because, well, it's late and I could very well have missed it.

Cheers!

**Comment by mnagel** [comment]
no, currently there is no feature like this.
