### ISSUE TITLE
Clustergit should consider 'main' to be the default branch

### ISSUE THREAD

**Issue by lhriley** [mnagel/clustergit#37]
Since `git`, Github, and the community at large have updated best practices to use the label `main` in place of `master` as the default branch name, `clustergit` should be updated to follow this pattern.

https://github.com/mnagel/clustergit/blob/78c4562e3e47253dccc91d49f1f1bd24d18a4fc2/clustergit#L216-L222

Reference:
https://github.com/github/renaming

**Comment by fpedroza** [comment]
I'd vote for the value here to be a regex or a comma-delimited list or something. I have repos that have transitioned to `main` and lots that haven't.

**Comment by lhriley** [comment]
I would agree with this in principal. Perhaps it might present an `INFO` or `WARN` message to prod users to update. If this was the case, include a flag or config file option to suppress the message entirely.

Something like:

```
WARNING: One or more repos are using the primary branch name 'master'. If you own these repos you are encouraged to update the branch name following community guidelines at https://github.com/github/renaming
```

**Comment by ChrisCarini** [comment]
I like the suggestion tat @fpedroza had to se RegEx - it allows more flexibility by the caller. I opened https://github.com/mnagel/clustergit/pull/40 with a small change to allow RegEx and changed the default to not warn for either `master` or `main`.

Unfortunately, there are cases where changing the branch name from `master` to `main` is a non-trivial task (I'm specifically thinking about corporate environments, where things are a bit slower to change for many reasons).

What do folks think? :)
