### ISSUE TITLE
Improve filtering of clustergit output

### ISSUE THREAD

**Issue by iainelder** [mnagel/clustergit#38]
I use clustergit in a [script](https://github.com/iainelder/dotfiles/blob/d7cec1ee01cf4cfb6750ba6454217999ab0476a0/bin/sync_all_repos.bash) that I run at the end of every session to ensure all my local repos have their changes committed and pushed before I log off.

The script filters the output of clustergit like this to operate on repos that need attention.

```bash
unclean="$(
  clustergit --branch '' --recursive --exclude=/\.terraform/ |
  grep ':' |
  grep -v Clean |
  awk '{print $1}'
)"

for repo in $unclean; do
  cd $unclean;
  ...
done
```

(The exclude option is to ignore temporary data created by the `terraform init` command that happen to be git repos.)

This used to work great until I started getting a weird error.

```
cd: Waiting: No such file or directory 
```
It turns out that an extra string is output for slower repos so that the first word of the line is not always the repo name. When the repo processing is complete the line no longer appears in the terminal but it remains in stdout. The '\r' means that in the terminal the line gets overwritten but in the stream it's prepended to the line.

https://github.com/mnagel/clustergit/blob/78c4562e3e47253dccc91d49f1f1bd24d18a4fc2/clustergit#L525

```
Scanning sub directories of .
Waiting for ./aws-notes .    (1/4)^M./aws-notes                             : ESC[93mUntracked filesESC[0m
./aws-solutions-architect-professional  : ESC[92mCleanESC[0m
./life-notes                            : ESC[92mCleanESC[0m
./foo                                   : ESC[91mChangesESC[0m
Done
```

I tried using `--quiet` and it does suppress the first "Scanning" line but not the "Waiting" line.

Would it be possible to make `--quiet` to suppress the "Waiting" message as well?

My current workaround is to add `tr '\r' '\n'` to the filter command.

**Comment by cipold** [comment]
Hi iainelder,

while I think your suggestion to skip the "waiting for" when `--quiet` is passed is a good addition, could you please try whether your issue is resolved using the `--print-asap` flag? This prints a directory status as soon as it is made available by any worker thread instead of keeping the order and thus no "waiting" on specific folders occurs. If you require a stable order you could set the `--workers 1` setting. This will make things slower as the parallelization is removed but you will have the same order on every execution.

**Comment by iainelder** [comment]
Hi @cipold , thanks for the suggestions.

You are right, using the `--print-asap` option does seem to avoid the "Waiting" message.

My data set is too small to notice any speedup through parallelism, so I will keep `--workers 1` set for this as well to keep the previous order.

These options for me are a cleaner way to solve my problem, so I will replace the workaround using tr.

Do you want to change the behavior of the `--quiet` flag after all? If not I suppose we can close this.
